name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Copy web files to Android assets
      run: |
        mkdir -p android/app/src/main/assets/www
        cp -r www/* android/app/src/main/assets/www/
        cp -r icons android/app/src/main/assets/www/
      
    - name: Build Release APK
      run: |
        cd android
        chmod +x ../gradlew
        ../gradlew assembleRelease --no-daemon
      
    - name: Sign APK
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > keystore.jks
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore keystore.jks \
          -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
          -keypass "${{ secrets.KEY_PASSWORD }}" \
          android/app/build/outputs/apk/release/app-release-unsigned.apk \
          "${{ secrets.KEY_ALIAS }}"
          
    - name: Zipalign APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
          android/app/build/outputs/apk/release/app-release-unsigned.apk \
          3d-model-viewer.apk
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: 3d-model-viewer
        path: 3d-model-viewer.apk
        retention-days: 30
